FROM node:14.7.0-alpine

ENV TZ=Asia/Bangkok
RUN apk update
RUN apk upgrade
RUN rm -rf /var/cache/apk/*

ARG mode

WORKDIR /app/Dark-DungeonFE
COPY . .

RUN npm install
RUN npm run ${mode}

CMD node server.js

